config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'request_password_reset', to: 'passwords#request_reset'
  post 'generate_password_reset_token', to: 'passwords#generate_reset_token'
  get 'reset_password/:reset_password_token', to: 'passwords#reset_password', as: 'reset_password'
  post 'update', to: 'passwords#update', as: 'update_password'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_MINIMUM_LENGTH = 8
  NAME_MINIMUM_LENGTH = 5
  validates :password, length: { minimum: PASSWORD_MINIMUM_LENGTH }, allow_blank: false, if: :require_password_validation?
  validates :name, length: { minimum: NAME_MINIMUM_LENGTH }, allow_blank: false, on: :update, if: :require_name_validation?
  validates_uniqueness_of :email
  validates_uniqueness_of :reset_password_token, on: :create
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  has_secure_password

  def require_name_validation?
    changed.include?("name")
  end

  def require_password_validation?
    changed.include?("password_digest")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :fetch_user, only: :update

  def request_reset;end

  def generate_reset_token
    user = User.find_by(email: user_params[:email])
    reset_token_service = ResetPasswordToken.new(user)

    reset_token_service.generate_token

    flash[:notice] = "The reset password link has been sent via email"
    redirect_back(fallback_location: request_password_reset_path)
  end

  def reset_psssword;end

  def update
    reset_token = ResetPasswordToken.new(@user)

    if !reset_token.valid?
      flash[:error] = "Invalid reset password link, please request reset password again"

      redirect_to(request_password_reset_path) and return
    end

    if @user.update_attributes(user_params)
      flash[:notice] = "Password updated"

      redirect_to new_session_path
    else
      flash[:error] = @user.errors.full_messages.first

      redirect_back(fallback_location: update_password_path)
    end
  end

  private

  def fetch_user
    @user = User.find_by(reset_password_token: user_params[:reset_password_token])
  end

  def user_params
    params.require(:user).permit(:email, :reset_password_token, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id

      flash[:notice] = "Welcome back, #{ user.name.capitalize }"
      redirect_to edit_user_path(user)
    else
      flash[:error] = "Incorrect Email or Password"

      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    flash[:notice] = "Successfully logged out"
    redirect_to new_session_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = user_params[:email].split("@").first

    if @user.save
      session[:user_id] = @user.id

      UserNotifications.with(user: @user).welcome_mail.deliver_now

      flash[:notice] = "Welcome, #{ @user.name }"
      redirect_to edit_user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.first

      redirect_to root_url
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update_attributes(user_params)
    else
      flash[:error] = @user.errors.full_messages.first
    end

    redirect_back(fallback_location: :edit)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/links" %>
    <%= render "shared/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
  <div id="notice" class="message warning">
    <div class="wrap">
      <%= flash[:notice] %>
      <div class="btn-close">
        <div class="icon-close"></div>
      </div>
    </div>
  </div>
<% end %>
<% if flash[:error] %>
  <div id="notice" class="message alert">
    <div class="wrap">
      <%= flash[:error] %>
      <div class="btn-close">
        <div class="icon-close"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_links.html.erb
<% if current_user %>
  <%= link_to "Log out", session_path(current_user), method: :delete %>
<% else %>
  <div>
    <%= link_to "Sign Up", new_user_path, action: :delete unless controller_name == "users" %>
  </div>
  <div>
    <%= link_to "Login", new_session_path, action: :delete unless controller_name == "sessions" %>
  </div>
  <div>
    <%= link_to "Forgot Password", request_password_reset_path unless controller_name == "passwords" %>
  </div>
<% end %>

app/views/user_notifications/reset_password_instruction.html.erb
<%= link_to "Reset", reset_password_url(@user.reset_password_token) %>

app/views/user_notifications/welcome_mail.html.erb
<h3>Welcome <%= @user.name %>!</h3>

app/views/users/edit.html.erb
<h3>User Profile</h3>
Email: <%= @user.email %>
<%= form_for @user, url: { action: "update" } do |f| %>
  <div>
    Name:
    <%= f.text_field :name %>
  </div>
  <div>
    Password:
    <%= f.text_field :password, type: "password" %>
  </div>
  <div>
    Password Confirmation:
    <%= f.text_field :password_confirmation, type: "password" %>
  </div>
  <%= f.submit "Update" %>
<% end %>

app/views/users/new.html.erb
<%= @user.email if @user %>
<%= form_for @user, url: { action: "create" } do |f| %>
  <div>
    Email
    <%= f.text_field :email %>
  </div>
  <div>
    Password
    <%= f.text_field :password, type: "password" %>
  </div>
  <div>
    Password Confirmtion
    <%= f.text_field :password_confirmation, type: "password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>